### ISSUE TITLE
The number of XTicks does not adjust automatically

### ISSUE THREAD

**Issue by tosapola** [IRIS-Solutions-Team/IRIS-Toolbox#108]
Hi,

Don’t know since what version but I’ve just noticed that currently the number of XTicks doesn’t adjust properly when we plot tseries and resize the figure (actually, it stays the same as the figure first appears).
I remember that back in earlier versions it adjusts automatically, doesn’t it?

Best,
Tosapol

**Comment by jaromir-benes** [comment]
Hi Tosapol

They didn't adjust, they were fixed. However, if you use the new class
Series instead of tseries, there is a new mechanism of plotting them (based
on the standard Matlab datetime class) which does the adjustment after
resizing. To make Series also the default class when e.g. databases are
returned from IRIS functions, start your IRIS sessions by running the new
iris.startup instead of irisstartup.

Best,
Jaromir

**Comment by tosapola** [comment]
I see.
Thank you so much.
