### ISSUE TITLE
irisstartup cannot find irisuserconfig.m (at least on Windows)

### ISSUE THREAD

**Issue by nul0m** [IRIS-Solutions-Team/IRIS-Toolbox#110]
this seems to be a problem in a call to `utils.exist('irisuserconfig.m', 'file')` -- it returns false if no full path to `irisuserconfig.m` provided. i mean `utils.exist(which('irisuserconfig.m'), 'file')` seems to solve the issue

**Comment by jaromir-benes** [comment]
Oops. This is because originally, we used the plain vanilla exist( )
function, which searches all folders on the Matlab path. Then, Michael
Johnston switched to a java based exist( ) function, which doesn't do that,
and we didn't notice/catch this. I'll bring back the plain vanilla and it
should work all right, and create a test with irisuserconfig.

**Comment by jaromir-benes** [comment]
Fixed in 20180222.
