### ISSUE TITLE
How to run unit tests

### ISSUE THREAD

**Issue by ak-83** [IRIS-Solutions-Team/IRIS-Toolbox#158]
I would like to understand how to run the 450+ unit tests on my machine for two reasons. One, to understand how the code works. Two, to make sure it is compatible with the latest Matlab version (at this stage 2018b).

Could you please post some documentation around how/where the unit tests reside and how to trigger them (e.g. with a test suite/framework perhaps)?

**Comment by nul0m** [comment]
Thanks for your question, Alex,

Really sorry for the confusion about testing, we are going to add new Matlab versions to our test server soon. 

The test suite resides in a dedicated repository: https://github.com/IRIS-Solutions-Team/IRIS-Test 
Feel free to run it on your 2018b using `runAllTests.m` But, in general, you should not worry as all the development is mainly done in the latest Matlab and the test suite is mostly used to ensure the backward compatibility.

**Comment by jaromir-benes** [comment]
Hi Alex

Again, an apology also from my side. As a rule, IRIS is ALWAYS compatible
with the latest Matlab, not only because we have access to developers
pre-releases and are able to make sure everything works alright well ahead
of each official release. The information stated on the iris-toolbox page
(about 2017b) is a mistake.

The tests (they are not strictly speaking only unit tests but a mix of unit
and system tests) can be cloned or downloaded from the repo Sergey emailed
you a link to earlier, and executed simply by running runAllTests from its
directory.

Best
Jaromir

**Comment by ak-83** [comment]
Thanks to both of you.

I'll download the tests and attempt to run them.

It's reassuring that IRIS is always being developed on the latest Matlab version.

Just the last question. How big is the developer community around this tool box and how widely is it used, especially in the enterprise economics community? I'm trying to gauge how long it will be around for while actively supported.

**Comment by jaromir-benes** [comment]
Hi Alex

The developer community includes three core developers -- but more
importantly, the IRIS support infrastructure is now deeply embedded in the
OGResearch corporate structure (with about 40 staff members). It's been
actually only in the last, say, two years that also business entities
(mostly commercial banks) started using IRIS in addition to central banks,
international organizations, etc.

Since IRIS is a core tool critical to OGResearch's business, it will
definitely remain an actively developed and supported project.

Best,
Jaromir

**Comment by ak-83** [comment]
Thank you. That is reassuring!
