### ISSUE TITLE
The option 'ZeroLine=' doesn't support vector graphic.

### ISSUE THREAD

**Issue by tosapola** [IRIS-Solutions-Team/IRIS-Toolbox#193]
Hi,

The figure created with dbplot() can be exported nicely to a vector graphic file (e.g. eps) EXCEPT when we set 'ZeroLine=' to true. The picture's quality drops substantially.
Can this be fixed?

Best,
Tosapol

**Comment by tosapola** [comment]
And the option 'highlight=' and 'vline=' too.

**Comment by tosapola** [comment]
[Solved]
It's all about MATLAB's renderer.
Use 'painters' instead of 'opengl'.

**Comment by jaromir-benes** [comment]
This is because I use 3rd dimension (the z-axis) to position the
highlights, zero lines (and other horizontal lines) and vertical lines in
the +visual package. I will try to recode this so that the issue does not
appear.

**Comment by jaromir-benes** [comment]
I've changed the mechanism of plotting the background objects (`visual.highlight`, `visual.zeroline`, `visual.hline`, `visual.vline`) so that the `print` function does not default to `opengl` (because of the z-axis coordinates). Now all should work all right without specifying the `-painters` option.
