### ISSUE TITLE
struct2obj make the loading extremely slow

### ISSUE THREAD

**Issue by mariusmjp** [IRIS-Solutions-Team/IRIS-Toolbox#197]
Hi Jaromir,

I remarked when I load the data from .mat the function struct2obj make the program really slow. In My example I loaded from the same path in IRIS2015 vs IRIS20190223 and the differences are huged
![struct2obj](https://user-images.githubusercontent.com/22647406/59062597-38adaa00-8874-11e9-9880-466f0f201a65.jpg)
:
[
![Issue_iris](https://user-images.githubusercontent.com/22647406/59062367-a0afc080-8873-11e9-8ea9-c5b7c9b4096b.jpg)
](url)

**Comment by jaromir-benes** [comment]
Hi

This is because you're loading time series objects created in a
(substantially) earlier version of IRIS. They're not compatible with the
new tseries and Series objects, Matlab hence cannot load them directly, and
they need to be reconstructed from an auxiliary struct.

If you create, save and load the time series object in the latest version
of IRIS, the struct2obj( ) function will be never called, and the load/save
times will be down to normal.

Hope this helps. Let me know if you there's any other issues.

Best
Jaromir

**Comment by mariusmjp** [comment]
Thank you very much Jaromir.

Last time when I sent the message I also figure out that struct2obj probably convert my old tseries (2015) to the new one but I didn't send the third snapshot . 
Let me explain what I did and also send you my last snapshot. After load it in 2019 which takes 4.34 secondes (highlight in red),  I saved my results (because I supposed that after load my all tseries in the workspace have been converted in 2019). I saved my results present in my workspace (save_iris2019_format.mat) and I loaded my new .mat. in iris 2019 (NB: the new load haven't called struct2obj anymore). 
This is the conclusion : the performance seems better but it still worse than what we have in iris 2015 (please check section highlight in Orange vs green).

![Issue_iris](https://user-images.githubusercontent.com/22647406/59209903-5e8bc500-8b7a-11e9-8e8c-c150a06e56c8.jpg)

**Comment by jaromir-benes** [comment]
Could you please email me (jaromir dot benes at gmail dot com) both the old
and the new mat files?

**Comment by jaromir-benes** [comment]
I profiled the old and new version of IRIS, and it looks that is is
Matlab's own overhead. I will investigate further but does not look very
hopeful :)

**Comment by jaromir-benes** [comment]
I investigated some more. The problem appears to be Matlab overhead kicking
in when saving and loading objects that are subclassed from some
superclass. The structure of the tseries (and Series) class has changed a
lot since 2015, and it now derives from a larger number of superclasses. At
this point, I don't see an obvious solution, unfortunately...

**Comment by jaromir-benes** [comment]
I'm now attempting to restructure the superclasses to accelerate the load and save times. Will be probably able to shave off some of the overhead, but certainly not to make equal the old version...

**Comment by mariusmjp** [comment]
I see thanks Jaromir!
