### ISSUE TITLE
simulate model with constraints

### ISSUE THREAD

**Issue by frnix** [IRIS-Solutions-Team/IRIS-Toolbox#219]
Hi,

Is there a way in IRIS to simulate a model with constraints on the value of a particular variable (i.e x > 0 for instance)?

dbout = simulate(model, dbinput, range,…, options, ‘x > 0’) 

Thank you,

Francis

**Comment by PatMcFarlane** [comment]
Hi Francis,

Not sure if this is still an issue for you.  If it is, I have found the equation-selective simulation method works really well for this.  Here are the steps I usually do:

1.  In your model file, hopefully you have some equation x=f(z).    You would replace this with:
 `x =# max(0 , f(z));`

The =# operator tells IRIS that this particular equation needs an exact non-linear solution when simulating.

2. When simulating the model, use the equation-selective method:

`s=simulate(M,d,startDate:endDate,'method=','selective');`

Note that if the x=0 constraint binding alters the form of other equations (e.g., via Kuhn-tucker conditions), you will need to get creative about how to specify these equations in order to have them work properly when the constraint binds.

-Patrick

**Comment by frnix** [comment]
Hi Patrick,

Thank you for your time and clear explanation. It was really helpful. 

Francis
