### ISSUE TITLE
Kalman filter issues

### ISSUE THREAD

**Issue by Nic2020** [IRIS-Solutions-Team/IRIS-Toolbox#223]
Hi,

I get different behaviors from the filter.m function using different IRIS versions.

In the best case, using IRIS 20190802, I get Warning message #1 below, generated from main_file.m in the matrix_debug.zip file attached.

In the worst case, using IRIS 20191213, I get Error message #1 below, generated from the exact same script main_file.m.

I have 3 questions:
1) I understand that the model fisc_c03.model in matrix_debug.zip is non-linear and quite demanding, but is there anything I can do to solve the matrix singularity problem using IRIS 20190802? I checked and the numerical results are not so bad.
2) Is there a way we can turn off all the messages coming from the solver in IRIS 20190802?
3) Why is IRIS 20191213 crashing?

Many thanks for any advice or help on this,

Nicholas

----------------------------------
Warning message #1
Warning: Matrix is close to singular or badly scaled. Results may be inaccurate. RCOND =
1.141226e-17. 
> In model/kalmanFilter>oneStepBackMse (line 1018)
  In model/kalmanFilter>getFilterMse (line 808)
  In model/kalmanFilter (line 313)
  In model/filter (line 319)
  In main_file (line 82)

----------------------------------
Error message #1 
Error using model/prepareSimulate1
Cannot access method 'prepareSimulate1' in class 'model'.

Error in shared.Kalman/kalmanFilter/prepareSimulate (line 637)
        sn = prepareSimulate1(this, sn, opt.Simulate, displayMode);

Error in shared.Kalman/kalmanFilter (line 131)
    prepareSimulate( );

Error in model/filter (line 424)
[obj, regOutp, hData] = kalmanFilter(this, inputArray, hData, @hdataassign, kalmanOpt);
%#ok<ASGLU>

Error in main_file (line 82)
[~,db_shk] = filter(m,db_filter,rngD, ...

[matrix_debug.zip](https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/files/3963430/matrix_debug.zip)

**Comment by jaromir-benes** [comment]
Hi Nicholas

The error message in 20191213 is simply a bug, which we're going to fix
right now, and I'll let you know asap. This also relates to the
introduction of a new class of model objects "Model" (with a capital M at
the beginning) and I'll explain that to you once we fix the behavior.

The singularity warning in the other case is caused by the fact that the
one-step ahead forecast MSE matrix for your observables is singular - in
other words, there's either not enough shocks that could explain the
observables (some of them are stochastically dependent) or you perhaps are
using two or more identical variables or their combinations as observable -
e.g. if p is the log of prices, y is the log of output and ny=p+y is
nominal output, having all three of them (p, y, ny) as observables would
generate exactly this kind of warning.

If the numeric results are all right, one possible solution is to use a
pseudoinverse instead of inverse. and we will implement that option right
now as well (a similar thing is currently available at the level of the
prediction step, but your problem here arises at the level of the smoothing
step).

Best
Jaromir

**Comment by jaromir-benes** [comment]
...Also, I noticed that you actually do not use the std and MSE results from the filter. In that case, I strongly recommend to use the option `'MeanOnly=', true` when running `filter( )`. The MSE matrices are then not evaluated and stored (unless necessary for the calculation mean values). Not only will this prevent the singularity message, but it should also accelerate your calculations.

I will send you your codes back with a few modifications.

Best
Jaromir

**Comment by jaromir-benes** [comment]
Hi Nicholas

I had a look into the model, and was able to figure out the singularity
problem.
You have two pairs of observables: (loper_cap_obs, loper_cap_ann_obs) and
(ldirect_prog_expenses_obs, ldirect_prog_expenses_ann_obs)

The measurement shock associated with the annual ones,
i.e. std_loper_cap_ann_obs_shk and std_ldirect_prog_expenses_ann_obs_shk
are effectively turned off (std of 1e-12).
Because at the beginning of the sample both the quarterly and the annual
observations are available, they conflict with each other creating thus a
stochastic singularity.

Setting their std devs to some reasonable numbers fixes the problem.

Also, I got the nonlinear Kalman prediction step up and running - will post
a new IRIS release later this weekend or on Monday.

I will also send you back your files amended. I'll be happy to have call on
this with you if you wish so,....

A few things for you to know

* There's now a new model object called Model (mind the capital letter at
the beginning) with the old model (lowercase) being deprecated. Please use
the Model objects from now on. The functionality is basically the same
expect for the solution algorithms and Plan objects. With a Model, you need
to use a Plan object (again, capitalized) and this new Plan object fixes
some little inconsistencies in the treatment of simultaneous anticipated
and unanticipated endogenized shocks.

* When calling the nonlinear prediction step in the kalman filter, in the
'Simulate=' option you don't have to use anything else than the
specification for the nonlinear solver, e.g. Method=Selective, and if
needed Solver=.... Because yours is a completely backward-looking model,
you don't have to se the Window= option (how many periods are solved to
obtains nonlinear expectations).

Again, I'd be happy to skype with your and explain to you the details.
There's e.g. a simple trick how to find out what went wrong when you see
the singularity message (which variables are to be blamed).

Best,
Jaromir

**Comment by Nic2020** [comment]
Děkuji moc Jaromír!

It is amazing that you are finding the time to help me.

Increasing the standard deviation of the observation shocks from 1e-12 to 1e-6 removed the matrix singularity issue.

m.std_loper_cap_ann_obs_shk             = 1e-6;
m.std_ldirect_prog_expenses_ann_obs_shk = 1e-6;

Another thing that fixes the same issue is to remove two variables from the list of measurement variables that are not actually truly observed (i.e. loper_cap_obs and ldirect_prog_expenses_obs). In fact, I was only interpolating them from yearly to quarterly at the beginning of the sample to help the filter. This does not seem to be necessary anymore.

I also removed the NonlinWindow option and added the MeanOnly one as you suggested.

On the technical side, I’m fine thanks to your help. I’m essentially just left with conceptual questions about how to best use the Kalman filter to answer my research question, since I see a few ways to do it at this point. I’d be happy to discuss this (and other topics) at your convenience during a 15-30 min. chat on Skype, but no worries at all if you do not have time. I’m perfectly happy with what I have now. 

Ještě jednou vám děkuji za pomoc.

Nicholas
