### ISSUE TITLE
Unobservable components filtering 

### ISSUE THREAD

**Issue by AndreyDO** [IRIS-Solutions-Team/IRIS-Toolbox#232]
Hi, comrads!

A simple question about unobservable components filtering with a linear model in IRIS. Say, I want to implement an HP filter in a state-space form. It implies that the trend part follows a random walk, which means there's no steady state, thus IRIS throws a corresponding warning. What's the better practice for implementing this kind of unobservable components models in IRIS?

Best,
Andrey

**Comment by jaromir-benes** [comment]
Hi Andrey

Do not actually worry about the warning. It's really just a reminder to the
modeler - printed simply because most of the time, most of us build our
models to be diff stationary, and if they are not, it usually means we've
made a typo/error in our model specification.

Computationally/numerically, there is absolutely no problem with I(2)
variables, and your state space specification is perfectly alright and
valid.

Best
Jaromir

**Comment by AndreyDO** [comment]
Thanks for the clarification! :)
