### ISSUE TITLE
Bug with simulation with opt.Solver

### ISSUE THREAD

**Issue by mariusmjp** [IRIS-Solutions-Team/IRIS-Toolbox#269]
I have a bug when I tried to run simulation the cause come from opt.solver please see my snapshot:
![Bugs_with_simulation_version20200811](https://user-images.githubusercontent.com/22647406/91088307-c6171e80-e61f-11ea-82f1-a811ca79a908.png)

**Comment by jaromir-benes** [comment]
Hi

I will post a new Iris release with this bug fixed tomorrow. Note that you
will also need to use the option display=false to get the progress bar
working on the screen (display=false turns off the reporting of iterations,
otherwise the progress bar cannot be displayed properly)

However, note that the model object (with a lowercase m) and the
corresponding plan object (with a lowercase p) are legacy objects, and are
no longer supported or further developed. They're only maintained for
backward compatibility reasons.

Try to switch to new Model and Plan objects (uppercase M, uppercase P) as
soon as possible. The same goes for irisstartup->iris.startup and
tseries->Series.

Best
Jaromir

**Comment by jaromir-benes** [comment]
Fixed in 20200829 (scheduled release).
