### ISSUE TITLE
question on jforecast

### ISSUE THREAD

**Issue by ikarib** [IRIS-Solutions-Team/IRIS-Toolbox#56]
```
[~,f] = filter(m,d,r,'relative=',false);
u = jforecast(m,f,r,'anticipate=',false);
```
Why are smoothed standard deviations different in f and u?

**Comment by ikarib** [comment]
Why is `StdScale` set to `1+1i` not `1` by default? Why does it have to be a complex number? Why does jforecast return nonzero standard deviation of measurement variables? Even if I set StdScale to one, standard deviations from jforecast are different from smoothed ones using Kalman filter. Why? Please explain how standard deviations are computed.

**Comment by jaromir-benes** [comment]
This should be fixed now. `StdScale` is now `1` by default, and it can be set to a different (possibly complex) number lying on the unit circle (in the first quadrant). The number determines how the currently assigned std devs in the model object are "distributed" between anticipate and unanticipated shocks.

Also, the std errors from `jforecast` should be now the same as those from the Kalman smoother. Please let me know if this is not the case under some circumstances.

The entire `jforecast` command needs a major overhaul anyway, since the way anticipated and unanticipated shocks are combined, makes little sense, an unfortunate legacy from the past.

Best
Jaromir
